name: CI

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Package release
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: ./scripts/package.sh
    - uses: actions/upload-artifact@v3
      if: ${{ github.event_name == 'workflow_dispatch' }}
      with:
        name: ocr-reader
        path: ./ocr-reader.zip
